In [1]:
L=[1,2,3,4,5]

In [2]:
from pandas import DataFrame as DF

In [3]:
Data1=DF(L)

In [4]:
Data1

0
0  1
1  2
2  3
3  4
4  5

In [5]:
L=[(1,2,3),(4,5,6),(7,8)]

In [6]:
Data2=DF(L)

In [7]:
Data2

0  1    2
0  1  2  3.0
1  4  5  6.0
2  7  8  NaN

In [8]:
T=([1,2,3],[4,5,6])

In [9]:
Data3=DF(T)

In [10]:
Data3

0  1  2
0  1  2  3
1  4  5  6

In [11]:
S={(1,2,3),(4,5,6)}

In [12]:
Data4=DF(S)

In [13]:
Data4

0  1  2
0  1  2  3
1  4  5  6

In [14]:
print(type(Data4))

<class 'pandas.core.frame.DataFrame'>


In [15]:
Data1.index

RangeIndex(start=0, stop=5, step=1)

In [16]:
Data2.index

RangeIndex(start=0, stop=3, step=1)

In [17]:
for i in Data1.index:
    print(i)

0
1
2
3
4


In [18]:
type(i)

int

In [19]:
Data1.index.dtype

dtype('int64')

In [20]:
Data2.columns

RangeIndex(start=0, stop=3, step=1)

In [21]:
for j in Data2.columns:
    print(j)

0
1
2


In [22]:
Data2.columns.dtype

dtype('int64')

In [23]:
Data1.values

array([[1],
       [2],
       [3],
       [4],
       [5]], dtype=int64)

In [24]:
Data2.values

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8., nan]])

In [25]:
type(Data2.values)

numpy.ndarray

In [26]:
Dict1={'Name':'Zachariah','empno':103,'Salary':22000}

In [27]:
Data11=DF(Dict1)

ValueError: If using all scalar values, you must pass an index

In [28]:
Data11=DF(Dict1,index=[1])

In [29]:
Data11

Name  empno  Salary
1  Zachariah    103   22000

In [30]:
Dict2={'Name':{'one':'Mohan','two':'Shahana','three':'Zachariah'},'empno':{'one':101,'two':102,'three':103},'Salary':{'one':14000,'two':20000,'three':22000}}

In [31]:
Data12=DF(Dict2)

In [32]:
Data12

Name  empno  Salary
one        Mohan    101   14000
two      Shahana    102   20000
three  Zachariah    103   22000

In [33]:
Dict3={'Name':['Mohan','Shahana','Zachariah'],'empno':[101,102,103],'Salary':[14000,20000,22000]}

In [34]:
Data13=DF(Dict3)

In [35]:
Data13

Name  empno  Salary
0      Mohan    101   14000
1    Shahana    102   20000
2  Zachariah    103   22000

In [36]:
Data=DF()

In [37]:
Data

Empty DataFrame
Columns: []
Index: []

In [38]:
type(Data)

pandas.core.frame.DataFrame

In [39]:
L11=[1]

In [40]:
Dat11=DF(L11)

In [41]:
Dat11

0
0  1

In [42]:
S11={1}

In [43]:
Dat12=DF(S11)

In [44]:
Dat12

0
0  1

In [45]:
T11=1,

In [46]:
Dat13=DF(T11)

In [47]:
Dat13

0
0  1

In [48]:
import pandas as pd

In [49]:
DataSet1=pd.read_csv('emp.csv')

In [50]:
DataSet1

E_Name  E_ID    E_Desig  E_Salary
0            K.Raj   101  scientist     54000
1     Mohan Raj M.   102   engineer     50000
2            M.Ram   103  scientist     80000
3        Ram Kumar   104  scientist     66000
4  Mohan Babu K.K.   106    officer     57000
5          K.Gopal   107  scientist     50000
6      Anil Raj M.   108   engineer     62000
7         Amala P.   201  scientist     70000
8             Uma    204    officer     60000
9             Suma   206   engineer     57000

In [51]:
DataSet1.values

array([['K.Raj', 101, 'scientist', 54000],
       ['Mohan Raj M.', 102, 'engineer', 50000],
       ['M.Ram', 103, 'scientist', 80000],
       ['Ram Kumar', 104, 'scientist', 66000],
       ['Mohan Babu K.K.', 106, 'officer', 57000],
       ['K.Gopal', 107, 'scientist', 50000],
       ['Anil Raj M.', 108, 'engineer', 62000],
       ['Amala P.', 201, 'scientist', 70000],
       ['Uma ', 204, 'officer', 60000],
       ['Suma', 206, 'engineer', 57000]], dtype=object)

In [52]:
DataSet1.size

40

In [53]:
DataSet1.shape

(10, 4)

In [54]:
DataSet1.ndim

2

In [55]:
DataSet1.reshape(2,5,4)

AttributeError: 'DataFrame' object has no attribute 'reshape'

In [56]:
DataSet1.values.reshape(2,5,4)

array([[['K.Raj', 101, 'scientist', 54000],
        ['Mohan Raj M.', 102, 'engineer', 50000],
        ['M.Ram', 103, 'scientist', 80000],
        ['Ram Kumar', 104, 'scientist', 66000],
        ['Mohan Babu K.K.', 106, 'officer', 57000]],

       [['K.Gopal', 107, 'scientist', 50000],
        ['Anil Raj M.', 108, 'engineer', 62000],
        ['Amala P.', 201, 'scientist', 70000],
        ['Uma ', 204, 'officer', 60000],
        ['Suma', 206, 'engineer', 57000]]], dtype=object)

In [57]:
DataSet1.index

RangeIndex(start=0, stop=10, step=1)

In [58]:
for col in DataSet1.columns:
    print(col)

E_Name
E_ID
E_Desig
E_Salary


In [59]:
DataSet1.columns

Index(['E_Name', 'E_ID', 'E_Desig', 'E_Salary'], dtype='object')

In [60]:
DataSet1['E_Name']

0              K.Raj
1       Mohan Raj M.
2              M.Ram
3          Ram Kumar
4    Mohan Babu K.K.
5            K.Gopal
6        Anil Raj M.
7           Amala P.
8               Uma 
9               Suma
Name: E_Name, dtype: object

In [61]:
DataSet1['E_ID']

0    101
1    102
2    103
3    104
4    106
5    107
6    108
7    201
8    204
9    206
Name: E_ID, dtype: int64

In [62]:
DataSet1['1']

KeyError: '1'

In [63]:
DataSet1.loc[1]

E_Name      Mohan Raj M.
E_ID                 102
E_Desig         engineer
E_Salary           50000
Name: 1, dtype: object

In [64]:
DataSet1.iloc[1]

E_Name      Mohan Raj M.
E_ID                 102
E_Desig         engineer
E_Salary           50000
Name: 1, dtype: object

In [65]:
DataSet1.iloc[:,1]

0    101
1    102
2    103
3    104
4    106
5    107
6    108
7    201
8    204
9    206
Name: E_ID, dtype: int64

In [66]:
DataSet1.loc[[1,3,5]]

E_Name  E_ID    E_Desig  E_Salary
1  Mohan Raj M.   102   engineer     50000
3     Ram Kumar   104  scientist     66000
5       K.Gopal   107  scientist     50000

In [67]:
DataSet1.loc[1:3]

E_Name  E_ID    E_Desig  E_Salary
1  Mohan Raj M.   102   engineer     50000
2         M.Ram   103  scientist     80000
3     Ram Kumar   104  scientist     66000

In [68]:
DataSet1.iloc[1,3]

50000

In [69]:
DataSet1.loc[2,'E_ID']

103

In [70]:
DataSet1.loc[2,'E_ID']=110

In [71]:
DataSet1

E_Name  E_ID    E_Desig  E_Salary
0            K.Raj   101  scientist     54000
1     Mohan Raj M.   102   engineer     50000
2            M.Ram   110  scientist     80000
3        Ram Kumar   104  scientist     66000
4  Mohan Babu K.K.   106    officer     57000
5          K.Gopal   107  scientist     50000
6      Anil Raj M.   108   engineer     62000
7         Amala P.   201  scientist     70000
8             Uma    204    officer     60000
9             Suma   206   engineer     57000

In [72]:
DataSet1.drop('E_ID')

KeyError: "['E_ID'] not found in axis"

In [73]:
DataSet1.drop('E_ID',axis=1)

E_Name    E_Desig  E_Salary
0            K.Raj  scientist     54000
1     Mohan Raj M.   engineer     50000
2            M.Ram  scientist     80000
3        Ram Kumar  scientist     66000
4  Mohan Babu K.K.    officer     57000
5          K.Gopal  scientist     50000
6      Anil Raj M.   engineer     62000
7         Amala P.  scientist     70000
8             Uma     officer     60000
9             Suma   engineer     57000

In [74]:
DataSet1

E_Name  E_ID    E_Desig  E_Salary
0            K.Raj   101  scientist     54000
1     Mohan Raj M.   102   engineer     50000
2            M.Ram   110  scientist     80000
3        Ram Kumar   104  scientist     66000
4  Mohan Babu K.K.   106    officer     57000
5          K.Gopal   107  scientist     50000
6      Anil Raj M.   108   engineer     62000
7         Amala P.   201  scientist     70000
8             Uma    204    officer     60000
9             Suma   206   engineer     57000

In [75]:
DataSet1.drop('E_ID',axis=1,inplace=True)

In [76]:
DataSet1

E_Name    E_Desig  E_Salary
0            K.Raj  scientist     54000
1     Mohan Raj M.   engineer     50000
2            M.Ram  scientist     80000
3        Ram Kumar  scientist     66000
4  Mohan Babu K.K.    officer     57000
5          K.Gopal  scientist     50000
6      Anil Raj M.   engineer     62000
7         Amala P.  scientist     70000
8             Uma     officer     60000
9             Suma   engineer     57000

In [77]:
PhoneNo=[932287278, 962287278, 914287275, 914287335, 962387278,932287278,962287278, 89287275,94287335, 962387278]


In [78]:
PhoneNo

[932287278,
 962287278,
 914287275,
 914287335,
 962387278,
 932287278,
 962287278,
 89287275,
 94287335,
 962387278]

In [79]:
DataSet1['PhoneNo']=PhoneNo

In [80]:
DataSet1

E_Name    E_Desig  E_Salary    PhoneNo
0            K.Raj  scientist     54000  932287278
1     Mohan Raj M.   engineer     50000  962287278
2            M.Ram  scientist     80000  914287275
3        Ram Kumar  scientist     66000  914287335
4  Mohan Babu K.K.    officer     57000  962387278
5          K.Gopal  scientist     50000  932287278
6      Anil Raj M.   engineer     62000  962287278
7         Amala P.  scientist     70000   89287275
8             Uma     officer     60000   94287335
9             Suma   engineer     57000  962387278

In [81]:
DataSet1.assign(Mobile=PhoneNo)

E_Name    E_Desig  E_Salary    PhoneNo     Mobile
0            K.Raj  scientist     54000  932287278  932287278
1     Mohan Raj M.   engineer     50000  962287278  962287278
2            M.Ram  scientist     80000  914287275  914287275
3        Ram Kumar  scientist     66000  914287335  914287335
4  Mohan Babu K.K.    officer     57000  962387278  962387278
5          K.Gopal  scientist     50000  932287278  932287278
6      Anil Raj M.   engineer     62000  962287278  962287278
7         Amala P.  scientist     70000   89287275   89287275
8             Uma     officer     60000   94287335   94287335
9             Suma   engineer     57000  962387278  962387278

In [82]:
DataSet1.assign(Mobile=PhoneNo,inplace=True)

E_Name    E_Desig  E_Salary    PhoneNo     Mobile  inplace
0            K.Raj  scientist     54000  932287278  932287278     True
1     Mohan Raj M.   engineer     50000  962287278  962287278     True
2            M.Ram  scientist     80000  914287275  914287275     True
3        Ram Kumar  scientist     66000  914287335  914287335     True
4  Mohan Babu K.K.    officer     57000  962387278  962387278     True
5          K.Gopal  scientist     50000  932287278  932287278     True
6      Anil Raj M.   engineer     62000  962287278  962287278     True
7         Amala P.  scientist     70000   89287275   89287275     True
8             Uma     officer     60000   94287335   94287335     True
9             Suma   engineer     57000  962387278  962387278     True

In [83]:
DataSet1

E_Name    E_Desig  E_Salary    PhoneNo
0            K.Raj  scientist     54000  932287278
1     Mohan Raj M.   engineer     50000  962287278
2            M.Ram  scientist     80000  914287275
3        Ram Kumar  scientist     66000  914287335
4  Mohan Babu K.K.    officer     57000  962387278
5          K.Gopal  scientist     50000  932287278
6      Anil Raj M.   engineer     62000  962287278
7         Amala P.  scientist     70000   89287275
8             Uma     officer     60000   94287335
9             Suma   engineer     57000  962387278

In [84]:
DataSet1.drop(1)

E_Name    E_Desig  E_Salary    PhoneNo
0            K.Raj  scientist     54000  932287278
2            M.Ram  scientist     80000  914287275
3        Ram Kumar  scientist     66000  914287335
4  Mohan Babu K.K.    officer     57000  962387278
5          K.Gopal  scientist     50000  932287278
6      Anil Raj M.   engineer     62000  962287278
7         Amala P.  scientist     70000   89287275
8             Uma     officer     60000   94287335
9             Suma   engineer     57000  962387278

In [85]:
import pandas as pd

In [86]:
DataSet2=pd.read_excel('Marks.xlsx')

In [87]:
DataSet2

Sr. No        Name of Student  Registration No   Marks
0        1     PAPPU JNANA MADHURI       2022UG1001     42
1        2              Ritesh Raj       2022UG1002     36
2        3         SHIVANSH RAJPUT       2022UG1003     48
3        4               ARION DAS       2022UG1004     44
4        5  KATRAVATH ROSHAN NAYAK       2022UG1005     20
..     ...                     ...              ...    ...
67      68            VISHAL VERMA       2022UG1068     44
68      69          DEVANSH MISHRA       2022UG1069     38
69      70     Amit kumar kushwaha       2022UG1070     30
70      71              YASH MEHTA       2022UG1071     24
71      72             ANKIT KUMAR       2022UG1072     54

[72 rows x 4 columns]

In [88]:
DataSet1=pd.read_excel('Marks.xlsx',sheet_name=0)

In [89]:
DataSet1

Sr. No        Name of Student  Registration No   Marks
0        1     PAPPU JNANA MADHURI       2022UG1001     42
1        2              Ritesh Raj       2022UG1002     36
2        3         SHIVANSH RAJPUT       2022UG1003     48
3        4               ARION DAS       2022UG1004     44
4        5  KATRAVATH ROSHAN NAYAK       2022UG1005     20
..     ...                     ...              ...    ...
67      68            VISHAL VERMA       2022UG1068     44
68      69          DEVANSH MISHRA       2022UG1069     38
69      70     Amit kumar kushwaha       2022UG1070     30
70      71              YASH MEHTA       2022UG1071     24
71      72             ANKIT KUMAR       2022UG1072     54

[72 rows x 4 columns]

In [90]:
DataSet2=pd.read_excel('Marks.xlsx',sheet_name=1)

In [91]:
DataSet2

Sr. No.  Name of Student  Registration No   Marks
0         1        AMIT KUMAR       2022UG1073     26
1         2       YATIN KUMAR       2022UG1074     40
2         3  Shivank Tripathi       2022UG1075     52
3         4     Anant Awasthi       2022UG1076     38
4         5        Khush Shah       2022UG1077     50
..      ...               ...              ...    ...
68       69   Rishabh Kashyap       2022UG3027     52
69       70           SAKSHAM       2022UG3028     40
70       71      MANISH MEENA       2022UG3029     24
71       72    SHREYANSH GOEL       2022UG2029     58
72       73    PRATHAM DIWEDI       2022UG4019     48

[73 rows x 4 columns]

In [92]:
DataSet2.to_string()

'    Sr. No.                     Name of Student  Registration No   Marks\n0         1                           AMIT KUMAR       2022UG1073     26\n1         2                          YATIN KUMAR       2022UG1074     40\n2         3                     Shivank Tripathi       2022UG1075     52\n3         4                        Anant Awasthi       2022UG1076     38\n4         5                           Khush Shah       2022UG1077     50\n5         6                      SHIVANSH SHUKLA       2022UG1078     30\n6         7                        RAJEEV RANJAN       2022UG1079     32\n7         8                   Abhishek kumar jha       2022UG1080     22\n8         9                        ABHINAV PATEL       2022UG1081     32\n9        10                       SAHIL REPURIYA       2022UG1082     42\n10       11                         SAHIL SHUKLA       2022UG1083     45\n11       12                        vishal mishra       2022UG1084     30\n12       13                  ABHISHEK

In [93]:
DataSet1.head()

Sr. No        Name of Student  Registration No   Marks
0       1     PAPPU JNANA MADHURI       2022UG1001     42
1       2              Ritesh Raj       2022UG1002     36
2       3         SHIVANSH RAJPUT       2022UG1003     48
3       4               ARION DAS       2022UG1004     44
4       5  KATRAVATH ROSHAN NAYAK       2022UG1005     20

In [94]:
DataSet1.tail()

Sr. No     Name of Student  Registration No   Marks
67      68         VISHAL VERMA       2022UG1068     44
68      69       DEVANSH MISHRA       2022UG1069     38
69      70  Amit kumar kushwaha       2022UG1070     30
70      71           YASH MEHTA       2022UG1071     24
71      72          ANKIT KUMAR       2022UG1072     54

In [95]:
DataSet1['Marks'].fillna(0,inplace=True)

In [96]:
DataSet1['Marks']

0     42
1     36
2     48
3     44
4     20
      ..
67    44
68    38
69    30
70    24
71    54
Name: Marks, Length: 72, dtype: int64

In [97]:
DataSet1['Marks'].sum()

2603

In [98]:
DataSet1['Marks'].mean()

36.15277777777778

In [99]:
DataSet1['Marks'].mode()[0]

48

In [100]:
import numpy as np

In [101]:
A=np.arange(1,17).reshape(4,4)

In [102]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [103]:
from pandas import DataFrame as DF

In [104]:
D_arr=DF(A,index='r1 r2 r3 r4'.split(),columns='c1 c2 c3 c4'.split())

In [105]:
D_arr

c1  c2  c3  c4
r1   1   2   3   4
r2   5   6   7   8
r3   9  10  11  12
r4  13  14  15  16

In [106]:
B=np.arange(21,37).reshape(4,4)

In [107]:
B

array([[21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [33, 34, 35, 36]])

In [108]:
D_arr2=DF(B,index='r1 r2 r3 r4'.split(),columns='c1 c2 c3 c4'.split())

In [109]:
D_arr2

c1  c2  c3  c4
r1  21  22  23  24
r2  25  26  27  28
r3  29  30  31  32
r4  33  34  35  36

In [110]:
D_arr+D_arr2

c1  c2  c3  c4
r1  22  24  26  28
r2  30  32  34  36
r3  38  40  42  44
r4  46  48  50  52

In [111]:
D_arr.add(D_arr2)

c1  c2  c3  c4
r1  22  24  26  28
r2  30  32  34  36
r3  38  40  42  44
r4  46  48  50  52

In [112]:
D_arr-D_arr2

c1  c2  c3  c4
r1 -20 -20 -20 -20
r2 -20 -20 -20 -20
r3 -20 -20 -20 -20
r4 -20 -20 -20 -20

In [113]:
D_arr*D_arr2

c1   c2   c3   c4
r1   21   44   69   96
r2  125  156  189  224
r3  261  300  341  384
r4  429  476  525  576

In [114]:
D_arr/D_arr2

c1        c2        c3        c4
r1  0.047619  0.090909  0.130435  0.166667
r2  0.200000  0.230769  0.259259  0.285714
r3  0.310345  0.333333  0.354839  0.375000
r4  0.393939  0.411765  0.428571  0.444444

In [115]:
D_arr.values@D_arr2.values

array([[ 290,  300,  310,  320],
       [ 722,  748,  774,  800],
       [1154, 1196, 1238, 1280],
       [1586, 1644, 1702, 1760]])

In [116]:
D_arr.loc['r1']

c1    1
c2    2
c3    3
c4    4
Name: r1, dtype: int32

In [117]:
D_arr.to_excel('Samp3.xlsx')

In [118]:
D_arr.to_excel('Samp4.xlsx',index=False)

In [119]:
D_arr

c1  c2  c3  c4
r1   1   2   3   4
r2   5   6   7   8
r3   9  10  11  12
r4  13  14  15  16

In [120]:
New_row={'c1':10,'c2':20,'c3':30,'c4':40}

In [121]:
D_arr=D_arr.add(New_row)

In [122]:
D_arr

c1  c2  c3  c4
r1  11  22  33  44
r2  15  26  37  48
r3  19  30  41  52
r4  23  34  45  56

In [123]:
D_arr_new=pd.concat([D_arr,D_arr2],ignore_index=True)

In [124]:
D_arr_new

c1  c2  c3  c4
0  11  22  33  44
1  15  26  37  48
2  19  30  41  52
3  23  34  45  56
4  21  22  23  24
5  25  26  27  28
6  29  30  31  32
7  33  34  35  36